FROM maven:3.8.6-openjdk-8-slim AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B -Dmaven.wagon.http.retryHandler.count=3 || true
COPY src ./src
RUN mvn clean package -DskipTests -Dmaven.test.skip=true -Dmaven.wagon.http.retryHandler.count=3

FROM eclipse-temurin:8-jre
WORKDIR /app
COPY --from=build /app/target/hotelbooking-0.0.1-SNAPSHOT.jar app.jar
COPY src/main/resources/ca.pem /app/ca.pem
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-docker} -jar app.jar"]