ALTER TABLE bookings
    ADD COLUMN first_name VARCHAR(100) NOT NULL,
    ADD COLUMN last_name VARCHAR(100) NOT NULL,
    ADD COLUMN phone VARCHAR(20) NOT NULL,
    ADD COLUMN email VARCHAR(100),
    MODIFY COLUMN customer_id BIGINT NULL;